Exercise 1

In [34]:
import numpy as np
np.set_printoptions(precision=4)

Part (a)

In [35]:
# Function to define A Matrix
def create_a_matrix(n):
    A = np.zeros([n, n])
    A[0, :2] = [2, -1]
    for i in range(1, n-1):
        A[i, i-1:i+2] = [-1, 2, -1]
    A[n-1, n-2:n] = [-1, 2]
    A = (n + 1)**2 * A
    
    return A

A = create_a_matrix(10)
print(A)

[[ 242. -121.    0.    0.    0.    0.    0.    0.    0.    0.]
 [-121.  242. -121.    0.    0.    0.    0.    0.    0.    0.]
 [   0. -121.  242. -121.    0.    0.    0.    0.    0.    0.]
 [   0.    0. -121.  242. -121.    0.    0.    0.    0.    0.]
 [   0.    0.    0. -121.  242. -121.    0.    0.    0.    0.]
 [   0.    0.    0.    0. -121.  242. -121.    0.    0.    0.]
 [   0.    0.    0.    0.    0. -121.  242. -121.    0.    0.]
 [   0.    0.    0.    0.    0.    0. -121.  242. -121.    0.]
 [   0.    0.    0.    0.    0.    0.    0. -121.  242. -121.]
 [   0.    0.    0.    0.    0.    0.    0.    0. -121.  242.]]


Getting the exact values λ_k = 4(n + 1)^2.sin^2(kπ2(n+1))

In [36]:
# Defining Lambda
def get_lambda_values(n):
    lambdas = list()
    for i in range(1, n + 1):
        lambdas.append(4 * (n + 1)**2 * np.sin((i * np.pi) / (2 * (n + 1)))**2)
        
    return lambdas

In [37]:
# Function defining QR_algorithmrithm
def QR_algorithm(A):
    Q = np.eye(A.shape[0])
    R = A
    for k in range(A.shape[1] - 1):
        x = R[k:, k]
        sign_x1 = x[0] / abs(x[0]) if x[0] != 0 else 1
        E1 = np.zeros_like(x)
        E1[0] = 1
        v = sign_x1 * np.linalg.norm(x) * E1 + x
        G = np.eye(len(x)) - 2 / np.dot(v, v.T) * np.outer(v, v)
        Q_i = np.eye(A.shape[0])
        Q_i[-G.shape[0]:, -G.shape[1]:] = G
        R = Q_i @ R
        Q = Q @ Q_i
    
    return Q, R

Q, R = QR_algorithm(A)

In [38]:
print(Q)

[[-0.8944 -0.3586 -0.1952 -0.1231 -0.0848 -0.062  -0.0473 -0.0373 -0.0302
   0.051 ]
 [ 0.4472 -0.7171 -0.3904 -0.2462 -0.1696 -0.124  -0.0947 -0.0747 -0.0604
   0.1019]
 [ 0.      0.5976 -0.5855 -0.3693 -0.2544 -0.1861 -0.142  -0.112  -0.0906
   0.1529]
 [ 0.      0.      0.6831 -0.4924 -0.3392 -0.2481 -0.1894 -0.1493 -0.1208
   0.2039]
 [ 0.      0.      0.      0.7385 -0.4241 -0.3101 -0.2367 -0.1866 -0.1509
   0.2548]
 [ 0.      0.      0.      0.      0.7774 -0.3721 -0.284  -0.224  -0.1811
   0.3058]
 [ 0.      0.      0.      0.      0.      0.8062 -0.3314 -0.2613 -0.2113
   0.3568]
 [ 0.      0.      0.      0.      0.      0.      0.8284 -0.2986 -0.2415
   0.4077]
 [ 0.      0.      0.      0.      0.      0.      0.      0.846  -0.2717
   0.4587]
 [ 0.      0.      0.      0.      0.      0.      0.      0.      0.8604
   0.5096]]


In [39]:
print(R)

[[-2.7056e+02  2.1645e+02 -5.4113e+01  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00]
 [ 2.3678e-14 -2.0247e+02  2.3140e+02 -7.2311e+01  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00]
 [ 1.2889e-14 -5.1891e-15 -1.7713e+02  2.3617e+02 -8.2659e+01  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00]
 [ 8.1284e-15 -3.2725e-15 -1.2575e-14 -1.6383e+02  2.3831e+02 -8.9364e+01
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00]
 [ 5.6005e-15 -2.2548e-15 -8.6642e-15 -7.8209e-15 -1.5564e+02  2.3945e+02
  -9.4069e+01  0.0000e+00  0.0000e+00  0.0000e+00]
 [ 4.0953e-15 -1.6488e-15 -6.3357e-15 -5.7190e-15 -3.8752e-15 -1.5008e+02
   2.4013e+02 -9.7553e+01  0.0000e+00  0.0000e+00]
 [ 3.1260e-15 -1.2585e-15 -4.8361e-15 -4.3654e-15 -2.9580e-15  1.0323e-14
  -1.4606e+02  2.4057e+02 -1.0024e+02  0.0000e+00]
 [ 2.4648e-15 -9.9234e-16 -3.8132e-15 -3.4420e-15 -2.3323e-15  8.1393e-15
   1.0476e-14 -1.4302e+02  2.4087e+02 -1.0237e+02]


In [40]:
# Tridiagonal Matrix
def tridiagonal_matrix(N, p):
    a = np.array([N[i, i-1] for i in range(1, N.shape[0])])
    b = np.array([N[i, i] for i in range(N.shape[0])])
    c = np.array([N[i, i+1] for i in range(N.shape[0] - 1)])
    u = [b[0]]
    v = [p[0]]
    for i in range(1, len(p)):
        l = a[i-1] / u[i-1]
        u.append(b[i] - l * c[i-1])
        v.append(p[i] - l * v[i-1])
    X = np.zeros(len(p))
    X[-1] = v[-1] / u[-1]
    for i in range(len(X) - 2, -1, -1):
        assert X[i] == 0
        X[i] = (v[i] - c[i] * X[i+1]) / u[i]

    return X

In [41]:
# Function to calculate the Eigen Values
def eigen_values(A, eps):
    eigen_values = list()
    while A.shape[0] > 1:
        H = A
        prev_d = 0
        while abs(A[-1, -2]) > eps:
            if prev_d == np.round(A[-1, -2], 4):
                # Perturbation if needed
                M = A[-1, -1] + 0.2
            else:
                M = A[-1, -1]
            prev_d = np.round(A[-1, -2], 4)
            Q, R = QR_algorithm(A - M * np.eye(A.shape[0]))
            A = R @ Q + M * np.eye(A.shape[0])
        eigen_values.append(A[-1, -1])
        A = A[:-1, :-1]        
    eigen_values.append(A[-1, -1])

    return eigen_values        

In [42]:
# Eigen Values of A from QR algorithm
eigen_from_algo = sorted(eigen_values(A, 1e-4))
print("Eigen Values from QR Algorithm: ")
eigen_from_algo

Eigen Values from QR Algorithm: 


[9.802700385291693,
 38.41664505486446,
 83.52370238524136,
 141.46956685354368,
 207.55980913786513,
 276.44019086213495,
 342.5304331464566,
 400.4762976147591,
 445.5833549451985,
 474.1972996146442]

In [43]:
lambdas = get_lambda_values(10)
print("Exact Eigen Values: ")
lambdas

Exact Eigen Values: 


[9.802700385291631,
 38.41664505485415,
 83.523702385241,
 141.46956685354348,
 207.55980913786502,
 276.440190862135,
 342.53043314645646,
 400.47629761475895,
 445.5833549451458,
 474.19729961470836]

In [44]:
difference_values = abs(np.subtract(eigen_from_algo, lambdas))
print("Difference between QR Algorithm and Exact Values: ")
difference_values.tolist()

Difference between QR Algorithm and Exact Values: 


[6.217248937900877e-14,
 1.0309975095879054e-11,
 3.694822225952521e-13,
 1.9895196601282805e-13,
 1.1368683772161603e-13,
 5.684341886080802e-14,
 1.1368683772161603e-13,
 1.7053025658242404e-13,
 5.269384928396903e-11,
 6.417621989385225e-11]

Part (b)

In [45]:
# Exact Eigen Vectors
def eigen_vectors(n):
    eigen_vector = list()
    
    for j in range(1, n + 1):
        eigen_vector.append(np.sin((np.pi * j) / (n + 1)))
        
    eigen_vector = np.array(eigen_vector)
    # Normalizing the values
    eigen_vector = eigen_vector / np.linalg.norm(eigen_vector)
    
    return eigen_vector

In [46]:
# Inverse Iteration
def inv_iter(A, theta, eps=0.001):
    prev_v = np.zeros(A.shape[0])
    V = np.ones(A.shape[0]) / np.linalg.norm(np.ones(A.shape[0]))
    while np.linalg.norm(abs(V) - abs(prev_v)) > eps:
        prev_v = V
        u = tridiagonal_matrix(A - theta * np.eye(len(V)), V)
        V = u / np.linalg.norm(u)
        
    return V

In [47]:
# Smallest Eigen Value of A
eigen_minval = min(eigen_values(A, 1e-4))
print("Smallest Eigen Value = ", eigen_minval)
print()
# Eigen Vector corresponding to smallest Eigen Value of A
eigen_from_inv_iter = inv_iter(A, eigen_minval)
print("Eigen Vectors from Inverse Iteration: ")
eigen_from_inv_iter.tolist()

Smallest Eigen Value =  9.802700385291693

Eigen Vectors from Inverse Iteration: 


[0.12013116587858114,
 0.23053001914523252,
 0.32225270127555117,
 0.38786838605913326,
 0.4220612809463162,
 0.4220612809463161,
 0.3878683860591332,
 0.32225270127555106,
 0.23053001914523238,
 0.12013116587858105]

In [48]:
print("Exact Eigen Vectors: ")
eigen_exact = eigen_vectors(10)
eigen_exact.tolist()

Exact Eigen Vectors: 


[0.12013116587858108,
 0.2305300191452324,
 0.32225270127555106,
 0.3878683860591332,
 0.4220612809463161,
 0.4220612809463162,
 0.38786838605913326,
 0.32225270127555106,
 0.23053001914523252,
 0.12013116587858108]

In [49]:
difference_vectors = abs(np.subtract(eigen_from_inv_iter, eigen_exact))
print("Difference between QR Algorithm and Exact Values: ")
difference_vectors.tolist()

Difference between QR Algorithm and Exact Values: 


[5.551115123125783e-17,
 1.1102230246251565e-16,
 1.1102230246251565e-16,
 5.551115123125783e-17,
 5.551115123125783e-17,
 5.551115123125783e-17,
 5.551115123125783e-17,
 0.0,
 1.3877787807814457e-16,
 2.7755575615628914e-17]